name: Auto Post From Issues

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'already' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 从issue创建文章
        run: |
          mkdir -p content/posts/${{ github.event.issue.title }}
          cat > "content/posts/${{ github.event.issue.title }}/${{ github.event.issue.title }}.md" << EOF
          ${{ github.event.issue.body }}
          EOF
