name: Auto Post From Issues

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'already' || github.event.label.name == 'pre-pub'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 从issue创建文章
        run: |
          label="${{ github.event.label.name }}"
          case "$label" in
          "already")
          mkdir -p "content/post/${{ github.event.issue.title }}"
          cat > "content/post/${{ github.event.issue.title }}/${{ github.event.issue.title }}.md" << 'EOF'
          ---
          ${{ github.event.issue.body }}
          EOF
          ;;
          "pre-pub")
          mkdir -p "content/post/${{ github.event.issue.title }}"
          cat > "content/post/${{ github.event.issue.title }}/${{ github.event.issue.title }}.md" << 'EOF'
          ---
          ${{ github.event.issue.body }}
          > 该文章为自动预发布，可能存在些许误差，请以already版本为主。
          EOF
          ;;
          esac
      
      - name: 提交PR
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "发布请求: ${{ github.event.issue.title}}"
          body: |
            文章将自动部署到: https://sout.eu.org
            将关闭以下issue: #${{ github.event.issue.number }}
      
      - name: Close Issue
        uses: peter-evans/close-issue@v3.0.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          close-reason: completed
