# 修改自 https://shazow.net/posts/github-issues-as-a-hugo-frontend/

name: Auto Post From Issues

on:
  issues:
    types: ['labeled']

jobs:
  build:
    if: ${{ github.event.label.name == 'already' || github.event.label.name == 'pre-pub'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 从issue创建文章
        run: |
          label="${{ github.event.label.name }}"
          case "$label" in
            "already")
              mkdir -p content/posts/${{ github.event.issue.title }}
              cat > "content/post/${{ github.event.issue.title }}/${{ github.event.issue.title }}.md" << EOF
              ${{ github.event.issue.body }}
              EOF
            ;;
            "pre-pub")
              mkdir -p content/posts/${{ github.event.issue.title }}
              cat > "content/post/${{ github.event.issue.title }}/${{ github.event.issue.title }}.md" << EOF
              这是预发布文章
              ${{ github.event.issue.body }}
              EOF
            ;;
          esac
      
      - name: 提交PR
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "发布请求: ${{ github.event.issue.title}}"
          body: |
            文章将自动部署到: https://sout.eu.org/p/${{ github.event.issue.title }}
            将关闭以下issue: #${{ github.event.issue.number }}
